name: .NET Console CI

on:
  push:
    branches: [main]

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Show current directory
        run: |
          pwd
          ls -R

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore dotnet-console-app/dotnet-console-app.csproj

      - name: Build
        run: dotnet build dotnet-console-app/dotnet-console-app.csproj --configuration Release --no-restore

      - name: Run
        run: dotnet run --project dotnet-console-app/dotnet-console-app.csproj --configuration Release --no-build
